name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:15
        env:
          POSTGRES_DB: secretary_pm
          POSTGRES_USER: secretary
          POSTGRES_PASSWORD: secretarypass
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U secretary" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build secretary image (with Chrome/ChromeDriver)
        run: |
          docker build \
            --build-arg INSTALL_CHROME=true \
            -t secretary-test .

      - name: Start secretary and db containers
        run: |
          docker compose up -d db
          # Wait for DB to be healthy
          until docker exec $(docker ps -qf "name=db") pg_isready -U secretary; do sleep 2; done
          docker compose up -d secretary
          # Wait for secretary to be ready
          sleep 20

      - name: Install Chrome and ChromeDriver in secretary container
        run: |
          docker exec $(docker ps -qf "name=secretary") bash -c '
            apt-get update && \
            apt-get install -y wget unzip && \
            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add - && \
            echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list && \
            apt-get update && \
            apt-get install -y google-chrome-stable && \
            CHROME_VERSION=$(google-chrome --version | grep -oP "[0-9.]+" | head -1) && \
            CHROMEDRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION%.*}) && \
            wget -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip && \
            unzip /tmp/chromedriver.zip -d /usr/local/bin && \
            chmod +x /usr/local/bin/chromedriver && \
            rm /tmp/chromedriver.zip'

      - name: Run tests in secretary container
        run: |
          docker exec $(docker ps -qf "name=secretary") pytest

      - name: Show secretary logs on failure
        if: failure()
        run: |
          docker logs $(docker ps -qf "name=secretary") 